#! /usr/bin/env bash

declare -A BAGS
declare -A MATCH

rule="^(.+) bags contain (.+)\.$"
bag_count_rule="^([0-9]+) (.+) bags?\.?$"

# bag_color="shiny gold"

parse_input() {
  local line
  while read -r line; do
    [[ $line =~ $rule ]] && {
      BAGS["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
    }
  done < "./input.txt"
}

search_contained() {
  [[ $1 ]] || return 1
  local contained=()
  local bag contains color # count
  for _bag in "${!BAGS[@]}"; do
    contains="${BAGS["$_bag"]}"
    IFS=$'\n' read -d "" -ra contained <<< "${contains//, /$'\n'}"
    for bag in "${contained[@]}"; do
      [[ $bag =~ $bag_count_rule ]] &&  {
        # count="${BASH_REMATCH[1]}"
        color="${BASH_REMATCH[2]}"
        [[ $color == "$1" ]] && {
          MATCH["$_bag"]=1
          search_contained "$_bag"
        }
      }
    done
  done
}

parse_input
search_contained "shiny gold"
echo "${#MATCH[@]}"
