#! /usr/bin/env bash

declare -a DATASET
mapfile -t DATASET < "./input.txt"

step=26

compute_pairs() {
  local i n a b v start=$1
  SUBDATASET=()
  v=0
  for ((i=start;i<start+step;i++)); do
    SUBDATASET+=("${DATASET[$((i-1))]}")
  done
  n="${SUBDATASET[$((${#SUBDATASET[@]}-1))]}"
  for a in "${SUBDATASET[@]}"; do
    ((a==n)) && break
    for b in "${SUBDATASET[@]}"; do
      ((b==a)) && continue
      ((b==n)) && continue
      ((a+b==n)) && { ((v++)); break; }
    done
    ((v>0)) && break
  done
  ((v==0)) && { echo "$n "; return 0; }
  return 1
}

next=0
while ((next<${#DATASET[@]})); do
  result=$(compute_pairs $((next+1))) && break
  ((next+=1))
done

echo $((result))
