#! /usr/bin/env bash

declare -a DATASET
mapfile -t DATASET < "./input.txt"

step=26

compute_pairs() {
  local i n a b v start=$1
  SUBDATASET=()
  v=0
  # echo -n "START=$start "
  for ((i=start;i<start+step;i++)); do
    SUBDATASET+=("${DATASET[$((i-1))]}")
  done
  n="${SUBDATASET[$((${#SUBDATASET[@]}-1))]}"
  # echo -n "| N=$n : "
  for a in "${SUBDATASET[@]}"; do
    ((a==n)) && break
    for b in "${SUBDATASET[@]}"; do
      ((b==a)) && continue
      ((b==n)) && continue
      # echo "$a+$b=$((a+b))"
      ((a+b==n)) && ((v++))
    done
  done
  ((v==0)) && { echo "$n "; return 0; }
  return 1
}

next=0
while ((next<${#DATASET[@]})); do
  # echo ">> $next"
  compute_pairs $((next+1)) && break
  ((next+=1))
done

